ALTER TABLE `block` ADD COLUMN `text_bold` TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE `block` ADD COLUMN `text_italic` TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE `block` ADD COLUMN `text_underline` TINYINT(1) NOT NULL DEFAULT 0;
